db:
  host:     "localhost"
  port:     5432
  user:     "postgres"
  password: ""                # set with environment variable APP_DB_PASSWORD
  dbname:   "cp_scheduler"
  sslmode:  "disable"
  
scheduler:
  interval: "2s"
  batch_size: 50

server:
  port: 8080
  shutdown_timeout_seconds: 10